spring.application.name=event-gateway

server.port=8080

spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

account.service.base-url=http://localhost:8081

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%level","service":"event-gateway","message":"%msg"}%n